export default{
    products: [
        {
            _id: '1',
            name: 'Hiskywin Full Zip Running Shirts',
            category: 'Shirts', 
            image: '/images/product-1.jpg',
            price: 60,
            brand: 'Hiskywin',
            Rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Nike Full Zip Hoodie Mens Workout Sweatshirt',
            category: 'Shirts', 
            image: '/images/product-2.jpg',
            price: 70,
            brand: 'Nike',
            Rating: 5,
            numReviews: 51,
            countInStock: 6,
        },
        {
            _id: '3',
            name: 'Adidas Mens Long Sleeve Hoodie',
            category: 'Shirts', 
            image: '/images/product-3.jpg',
            price: 90,
            brand: 'Adidas',
            Rating: 4,
            numReviews: 45,
            countInStock: 6,
        },
        {
            _id: '4',
            name: 'Under Armour Mens Soportstyle Tricot Joggers',
            category: 'Pants', 
            image: '/images/product-4.jpg',
            price: 90,
            brand: 'Under Armour',
            Rating: 2.5,
            numReviews: 198,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'Champion Mens Graphic Powerblend Fleece Jogger',
            category: 'Shirts', 
            image: '/images/product-5.jpg',
            price: 119,
            brand: 'Champion',
            Rating: 3.5,
            numReviews: 89,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
            category: 'Pants', 
            image: '/images/product-6.jpg',
            price: 85,
            brand: 'Aelfric Eden',
            Rating: 4.5,
            numReviews: 45,
            countInStock: 6,
        },
    ]
}